variable "rg_name" {}
variable "rg_location" {}
variable "nic_name" {}
variable "vnet_name" {}
variable "subnet_name" {}
variable "public_ip_name" {}
variable "nsg_name" {}
variable "pip_id" {}
variable "subnet_id" {}
